# Generated by Django 2.2.3 on 2019-07-28 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='titanic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pclass', models.IntegerField()),
                ('Sex', models.IntegerField()),
                ('Age', models.IntegerField()),
                ('SibSp', models.IntegerField()),
                ('Parch', models.IntegerField()),
                ('Fare', models.IntegerField()),
                ('Cabin', models.IntegerField()),
                ('Lname', models.IntegerField()),
                ('NamePrefix', models.IntegerField()),
            ],
        ),
    ]
