# Generated by Django 2.2.3 on 2019-07-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register_case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('uid', models.CharField(max_length=50)),
                ('vehical_no', models.CharField(max_length=50)),
                ('mobile_no', models.IntegerField()),
                ('dob', models.DateField()),
                ('case_date', models.DateField()),
                ('case_resgister', models.DateField()),
                ('case_type', models.CharField(choices=[('Accident', 'Accident'), ('Murder', 'Murder'), ('Rape', 'Rape')], default='JANUARY', max_length=9)),
            ],
        ),
    ]
