# Generated by Django 2.2.3 on 2019-07-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_case',
            name='reasone',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
