# Generated by Django 2.2.3 on 2019-07-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190727_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_case',
            name='address',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='register_case',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='register_case',
            name='long',
            field=models.FloatField(),
        ),
    ]
